<?php

/**
 * @file
 * This file is not used by Slick 3.x, but likely by contrib till updated.
 *
 * The relevant functions have been moved into the main module file to avoid
 * accidental removal so this file is no longer needed to be imported.
 *
 * @deprecated to be removed once Slick Views, etc. migrated to 3.x.
 */

/**
 * To be removed.
 */
function slick_get_responsive_options($count = 0) {
  return [];
}

/**
 * To be removed.
 */
function slick_clean_options(array $options) {
  return $options;
}

/**
 * To be removed.
 */
function slick_get_overridable_options() {
  return [];
}

/**
 * To be removed.
 */
function slick_layouts() {
  return [];
}

/**
 * To be removed.
 */
function slick_optionset_exists($optionset_name) {
  return FALSE;
}

/**
 * To be removed.
 */
function slick_optionset_load_all($reset = FALSE) {
  return [];
}

/**
 * To be removed.
 */
function slick_get_top_elements(array &$elements, $settings, &$form_state) {
  // Do nothing.
}

/**
 * To be removed.
 */
function slick_get_fieldable_elements(array &$elements, $settings, $definition = []) {
  // Do nothing.
}

/**
 * To be removed.
 */
function slick_get_elements(array &$elements, $settings, &$form_state) {
  // Do nothing.
}

/**
 * To be removed.
 */
function slick_get_grid_elements(array &$elements, $settings, &$form_state) {
  // Do nothing.
}

/**
 * To be removed.
 */
function slick_get_admin_assets(array &$elements, $settings = [], &$form = []) {
  // Do nothing.
}

/**
 * To be removed.
 */
function slick_get_admin_summary($field, $instance, $view_mode, $module) {
  // Do nothing.
}

/**
 * To be removed.
 */
function _slick_typecast_optionset(array &$options = array(), $breakpoints = 0) {
  // Do nothing.
}
